<?php

namespace Database\Seeders;

use App\Models\PublicCurrency;
use Illuminate\Database\Seeder;

class PublicCurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $currencies = [
            ["code" => "AFN", "name_en" => "AFN - Afghan Afghani", "name_ar" => "Afghan Afghani"],
            ["code" => "ALL", "name_en" => "ALL - Albanian Lek", "name_ar" => "ليك ألباني"],
            ["code" => "DZD", "name_en" => "DZD - Algerian Dinar", "name_ar" => "الدينار الجزائري"],
            ["code" => "AOA", "name_en" => "AOA - Angolan Kwanza", "name_ar" => "كوانزا الأنغولي"],
            ["code" => "ARS", "name_en" => "ARS - Argentine Peso", "name_ar" => "بيزو أرجنتيني"],
            ["code" => "AMD", "name_en" => "AMD - Armenian Dram", "name_ar" => "درام أرميني"],
            ["code" => "AWG", "name_en" => "AWG - Aruban Florin", "name_ar" => "أروبا فلورين"],
            ["code" => "AUD", "name_en" => "AUD - Australian Dollar", "name_ar" => "دولار استرالي"],
            ["code" => "AZN", "name_en" => "AZN - Azerbaijani Manat", "name_ar" => "مانات الأذربيجانية"],
            ["code" => "BSD", "name_en" => "BSD - Bahamian Dollar", "name_ar" => "الدولار الباهامي"],
            ["code" => "BHD", "name_en" => "BHD - Bahraini Dinar", "name_ar" => "الدينار البحريني"],
            ["code" => "BDT", "name_en" => "BDT - Bangladeshi Taka", "name_ar" => "تاكا بنجلاديشي"],
            ["code" => "BBD", "name_en" => "BBD - Barbadian Dollar", "name_ar" => "دولار بربادوسي"],
            ["code" => "BYR", "name_en" => "BYR - Belarusian Ruble", "name_ar" => "روبل بيلاروسي"],
            ["code" => "BEF", "name_en" => "BEF - Belgian Franc", "name_ar" => "فرنك بلجيكي"],
            ["code" => "BZD", "name_en" => "BZD - Belize Dollar", "name_ar" => "دولار بليز"],
            ["code" => "BMD", "name_en" => "BMD - Bermudan Dollar", "name_ar" => "الدولار البرمودي"],
            ["code" => "BTN", "name_en" => "BTN - Bhutanese Ngultrum", "name_ar" => "نولترم البوتاني"],
            ["code" => "BTC", "name_en" => "BTC - Bitcoin", "name_ar" => "بيتكوين"],
            ["code" => "BOB", "name_en" => "BOB - Bolivian Boliviano", "name_ar" => "بوليفيانو بوليفي"],
            ["code" => "BAM", "name_en" => "BAM - Bosnia-Herzegovina Convertible Mark", "name_ar" => "مارك البوسنة والهرسك قابل للتحويل"],
            ["code" => "BWP", "name_en" => "BWP - Botswanan Pula", "name_ar" => "بوتسوانا بولا"],
            ["code" => "BRL", "name_en" => "BRL - Brazilian Real", "name_ar" => "ريال برازيلي"],
            ["code" => "GBP", "name_en" => "GBP - British Pound Sterling", "name_ar" => "الجنيه الاسترليني البريطاني"],
            ["code" => "BND", "name_en" => "BND - Brunei Dollar", "name_ar" => "دولار بروناي"],
            ["code" => "BGN", "name_en" => "BGN - Bulgarian Lev", "name_ar" => "ليف بلغاري"],
            ["code" => "BIF", "name_en" => "BIF - Burundian Franc", "name_ar" => "فرنك بوروندي"],
            ["code" => "KHR", "name_en" => "KHR - Cambodian Riel", "name_ar" => "الريال الكمبودي"],
            ["code" => "CAD", "name_en" => "CAD - Canadian Dollar", "name_ar" => "دولار كندي"],
            ["code" => "CVE", "name_en" => "CVE - Cape Verdean Escudo", "name_ar" => "اسكودو الرأس الأخضر"],
            ["code" => "KYD", "name_en" => "KYD - Cayman Islands Dollar", "name_ar" => "دولار جزر كايمان"],
            ["code" => "XPF", "name_en" => "XPF - CFP Franc", "name_ar" => "فرنك سي إف بي"],
            ["code" => "CLP", "name_en" => "CLP - Chilean Peso", "name_ar" => "بيزو تشيلي"],
            ["code" => "CNY", "name_en" => "CNY - Chinese Yuan", "name_ar" => "اليوان الصيني"],
            ["code" => "COP", "name_en" => "COP - Colombian Peso", "name_ar" => "بيزو كولومبي"],
            ["code" => "KMF", "name_en" => "KMF - Comorian Franc", "name_ar" => "فرنك جزر القمر"],
            ["code" => "CDF", "name_en" => "CDF - Congolese Franc", "name_ar" => "فرنك كونغولي"],
            ["code" => "CRC", "name_en" => "CRC - Costa Rican ColÃ³n", "name_ar" => "كوستاريكا كولون"],
            ["code" => "HRK", "name_en" => "HRK - Croatian Kuna", "name_ar" => "كونا الكرواتية"],
            ["code" => "CUC", "name_en" => "CUC - Cuban Convertible Peso", "name_ar" => "بيزو كوبي قابل للتحويل"],
            ["code" => "CZK", "name_en" => "CZK - Czech Republic Koruna", "name_ar" => "جمهورية الكورونا التشيكية"],
            ["code" => "DKK", "name_en" => "DKK - Danish Krone", "name_ar" => "كرونة دنماركية"],
            ["code" => "DJF", "name_en" => "DJF - Djiboutian Franc", "name_ar" => "فرنك جيبوتي"],
            ["code" => "DOP", "name_en" => "DOP - Dominican Peso", "name_ar" => "بيزو دومنيكاني"],
            ["code" => "XCD", "name_en" => "XCD - East Caribbean Dollar", "name_ar" => "دولار شرق الكاريبي"],
            ["code" => "EGP", "name_en" => "EGP - Egyptian Pound", "name_ar" => "الجنيه المصري"],
            ["code" => "ERN", "name_en" => "ERN - Eritrean Nakfa", "name_ar" => "الناكفا الإريترية"],
            ["code" => "EEK", "name_en" => "EEK - Estonian Kroon", "name_ar" => "الإستونية كرون"],
            ["code" => "ETB", "name_en" => "ETB - Ethiopian Birr", "name_ar" => "بر اثيوبي"],
            ["code" => "EUR", "name_en" => "EUR - Euro", "name_ar" => "اليورو"],
            ["code" => "FKP", "name_en" => "FKP - Falkland Islands Pound", "name_ar" => "جنيه جزر فوكلاند"],
            ["code" => "FJD", "name_en" => "FJD - Fijian Dollar", "name_ar" => "دولار فيجي"],
            ["code" => "GMD", "name_en" => "GMD - Gambian Dalasi", "name_ar" => "Gambian Dalasi"],
            ["code" => "GEL", "name_en" => "GEL - Georgian Lari", "name_ar" => "اللاري الجورجية"],
            ["code" => "DEM", "name_en" => "DEM - German Mark", "name_ar" => "المارك الألماني"],
            ["code" => "GHS", "name_en" => "GHS - Ghanaian Cedi", "name_ar" => "سيدي الغاني"],
            ["code" => "GIP", "name_en" => "GIP - Gibraltar Pound", "name_ar" => "جبل طارق الجنيه"],
            ["code" => "GRD", "name_en" => "GRD - Greek Drachma", "name_ar" => "دراخما اليونانية"],
            ["code" => "GTQ", "name_en" => "GTQ - Guatemalan Quetzal", "name_ar" => "كوتزال غواتيمالا"],
            ["code" => "GNF", "name_en" => "GNF - Guinean Franc", "name_ar" => "فرنك غينيا"],
            ["code" => "GYD", "name_en" => "GYD - Guyanaese Dollar", "name_ar" => "دولار جوياني"],
            ["code" => "HTG", "name_en" => "HTG - Haitian Gourde", "name_ar" => "الجورد الهايتي"],
            ["code" => "HNL", "name_en" => "HNL - Honduran Lempira", "name_ar" => "هندوراس لمبيرا"],
            ["code" => "HKD", "name_en" => "HKD - Hong Kong Dollar", "name_ar" => "الدولار هونج كونج"],
            ["code" => "HUF", "name_en" => "HUF - Hungarian Forint", "name_ar" => "فورنت مجري"],
            ["code" => "ISK", "name_en" => "ISK - Icelandic KrÃ³na", "name_ar" => "آيسلندية KrÃ³na"],
            ["code" => "INR", "name_en" => "INR - Indian Rupee", "name_ar" => "الروبية الهندية"],
            ["code" => "IDR", "name_en" => "IDR - Indonesian Rupiah", "name_ar" => "الروبية الاندونيسية"],
            ["code" => "IRR", "name_en" => "IRR - Iranian Rial", "name_ar" => "ريال ايراني"],
            ["code" => "IQD", "name_en" => "IQD - Iraqi Dinar", "name_ar" => "الدينار العراقي"],
            ["code" => "ITL", "name_en" => "ITL - Italian Lira", "name_ar" => "ليرة ايطالية"],
            // ["code" => "ILS", "name_en" => "ILS - Israeli New Sheqel", "name_ar" => null],
            ["code" => "JMD", "name_en" => "JMD - Jamaican Dollar", "name_ar" => "الدولار الجامايكي"],
            ["code" => "JPY", "name_en" => "JPY - Japanese Yen", "name_ar" => "الين الياباني"],
            ["code" => "JOD", "name_en" => "JOD - Jordanian Dinar", "name_ar" => "الدينار الأردني"],
            ["code" => "KZT", "name_en" => "KZT - Kazakhstani Tenge", "name_ar" => "التنج الكازاخستاني"],
            ["code" => "KES", "name_en" => "KES - Kenyan Shilling", "name_ar" => "شلن كيني"],
            ["code" => "KWD", "name_en" => "KWD - Kuwaiti Dinar", "name_ar" => "الدينار الكويتي"],
            ["code" => "KGS", "name_en" => "KGS - Kyrgystani Som", "name_ar" => "قرغيزستاني سوم"],
            ["code" => "LAK", "name_en" => "LAK - Laotian Kip", "name_ar" => "لاوس كيب"],
            ["code" => "LVL", "name_en" => "LVL - Latvian Lats", "name_ar" => "لاتس لاتفيا"],
            ["code" => "LBP", "name_en" => "LBP - Lebanese Pound", "name_ar" => "الليرة البنانية"],
            ["code" => "LSL", "name_en" => "LSL - Lesotho Loti", "name_ar" => "لوتي ليسوتو"],
            ["code" => "LRD", "name_en" => "LRD - Liberian Dollar", "name_ar" => null],
            ["code" => "LYD", "name_en" => "LYD - Libyan Dinar", "name_ar" => null],
            ["code" => "LTL", "name_en" => "LTL - Lithuanian Litas", "name_ar" => null],
            ["code" => "MOP", "name_en" => "MOP - Macanese Pataca", "name_ar" => null],
            ["code" => "MKD", "name_en" => "MKD - Macedonian Denar", "name_ar" => null],
            ["code" => "MGA", "name_en" => "MGA - Malagasy Ariary", "name_ar" => null],
            ["code" => "MWK", "name_en" => "MWK - Malawian Kwacha", "name_ar" => null],
            ["code" => "MYR", "name_en" => "MYR - Malaysian Ringgit", "name_ar" => null],
            ["code" => "MVR", "name_en" => "MVR - Maldivian Rufiyaa", "name_ar" => null],
            ["code" => "MRO", "name_en" => "MRO - Mauritanian Ouguiya", "name_ar" => null],
            ["code" => "MUR", "name_en" => "MUR - Mauritian Rupee", "name_ar" => null],
            ["code" => "MXN", "name_en" => "MXN - Mexican Peso", "name_ar" => null],
            ["code" => "MDL", "name_en" => "MDL - Moldovan Leu", "name_ar" => null],
            ["code" => "MNT", "name_en" => "MNT - Mongolian Tugrik", "name_ar" => null],
            ["code" => "MAD", "name_en" => "MAD - Moroccan Dirham", "name_ar" => null],
            ["code" => "MZM", "name_en" => "MZM - Mozambican Metical", "name_ar" => null],
            ["code" => "MMK", "name_en" => "MMK - Myanmar Kyat", "name_ar" => null],
            ["code" => "NAD", "name_en" => "NAD - Namibian Dollar", "name_ar" => null],
            ["code" => "NPR", "name_en" => "NPR - Nepalese Rupee", "name_ar" => null],
            ["code" => "ANG", "name_en" => "ANG - Netherlands Antillean Guilder", "name_ar" => null],
            ["code" => "TWD", "name_en" => "TWD - New Taiwan Dollar", "name_ar" => null],
            ["code" => "NZD", "name_en" => "NZD - New Zealand Dollar", "name_ar" => null],
            ["code" => "NIO", "name_en" => "NIO - Nicaraguan CÃ³rdoba", "name_ar" => null],
            ["code" => "NGN", "name_en" => "NGN - Nigerian Naira", "name_ar" => null],
            ["code" => "KPW", "name_en" => "KPW - North Korean Won", "name_ar" => null],
            ["code" => "NOK", "name_en" => "NOK - Norwegian Krone", "name_ar" => null],
            ["code" => "OMR", "name_en" => "OMR - Omani Rial", "name_ar" => null],
            ["code" => "PKR", "name_en" => "PKR - Pakistani Rupee", "name_ar" => null],
            ["code" => "PAB", "name_en" => "PAB - Panamanian Balboa", "name_ar" => null],
            ["code" => "PGK", "name_en" => "PGK - Papua New Guinean Kina", "name_ar" => null],
            ["code" => "PYG", "name_en" => "PYG - Paraguayan Guarani", "name_ar" => null],
            ["code" => "PEN", "name_en" => "PEN - Peruvian Nuevo Sol", "name_ar" => null],
            ["code" => "PHP", "name_en" => "PHP - Philippine Peso", "name_ar" => null],
            ["code" => "PLN", "name_en" => "PLN - Polish Zloty", "name_ar" => null],
            ["code" => "QAR", "name_en" => "QAR - Qatari Rial", "name_ar" => null],
            ["code" => "RON", "name_en" => "RON - Romanian Leu", "name_ar" => null],
            ["code" => "RUB", "name_en" => "RUB - Russian Ruble", "name_ar" => null],
            ["code" => "RWF", "name_en" => "RWF - Rwandan Franc", "name_ar" => null],
            ["code" => "SVC", "name_en" => "SVC - Salvadoran ColÃ³n", "name_ar" => null],
            ["code" => "WST", "name_en" => "WST - Samoan Tala", "name_ar" => null],
            ["code" => "SAR", "name_en" => "SAR - Saudi Riyal", "name_ar" => null],
            ["code" => "RSD", "name_en" => "RSD - Serbian Dinar", "name_ar" => null],
            ["code" => "SCR", "name_en" => "SCR - Seychellois Rupee", "name_ar" => null],
            ["code" => "SLL", "name_en" => "SLL - Sierra Leonean Leone", "name_ar" => null],
            ["code" => "SGD", "name_en" => "SGD - Singapore Dollar", "name_ar" => null],
            ["code" => "SKK", "name_en" => "SKK - Slovak Koruna", "name_ar" => null],
            ["code" => "SBD", "name_en" => "SBD - Solomon Islands Dollar", "name_ar" => null],
            ["code" => "SOS", "name_en" => "SOS - Somali Shilling", "name_ar" => null],
            ["code" => "ZAR", "name_en" => "ZAR - South African Rand", "name_ar" => null],
            ["code" => "KRW", "name_en" => "KRW - South Korean Won", "name_ar" => null],
            ["code" => "XDR", "name_en" => "XDR - Special Drawing Rights", "name_ar" => null],
            ["code" => "LKR", "name_en" => "LKR - Sri Lankan Rupee", "name_ar" => null],
            ["code" => "SHP", "name_en" => "SHP - St. Helena Pound", "name_ar" => null],
            ["code" => "SDG", "name_en" => "SDG - Sudanese Pound", "name_ar" => null],
            ["code" => "SRD", "name_en" => "SRD - Surinamese Dollar", "name_ar" => null],
            ["code" => "SZL", "name_en" => "SZL - Swazi Lilangeni", "name_ar" => null],
            ["code" => "SEK", "name_en" => "SEK - Swedish Krona", "name_ar" => null],
            ["code" => "CHF", "name_en" => "CHF - Swiss Franc", "name_ar" => null],
            ["code" => "SYP", "name_en" => "SYP - Syrian Pound", "name_ar" => null],
            ["code" => "STD", "name_en" => "STD - São Tomé and Príncipe Dobra", "name_ar" => null],
            ["code" => "TJS", "name_en" => "TJS - Tajikistani Somoni", "name_ar" => null],
            ["code" => "TZS", "name_en" => "TZS - Tanzanian Shilling", "name_ar" => null],
            ["code" => "THB", "name_en" => "THB - Thai Baht", "name_ar" => null],
            ["code" => "TOP", "name_en" => "TOP - Tongan pa'anga", "name_ar" => null],
            ["code" => "TTD", "name_en" => "TTD - Trinidad & Tobago Dollar", "name_ar" => null],
            ["code" => "TND", "name_en" => "TND - Tunisian Dinar", "name_ar" => null],
            ["code" => "TRY", "name_en" => "TRY - Turkish Lira", "name_ar" => null],
            ["code" => "TMT", "name_en" => "TMT - Turkmenistani Manat", "name_ar" => null],
            ["code" => "UGX", "name_en" => "UGX - Ugandan Shilling", "name_ar" => null],
            ["code" => "UAH", "name_en" => "UAH - Ukrainian Hryvnia", "name_ar" => null],
            ["code" => "AED", "name_en" => "AED - United Arab Emirates Dirham", "name_ar" => null],
            ["code" => "UYU", "name_en" => "UYU - Uruguayan Peso", "name_ar" => null],
            ["code" => "USD", "name_en" => "USD - US Dollar", "name_ar" => null],
            ["code" => "UZS", "name_en" => "UZS - Uzbekistan Som", "name_ar" => null],
            ["code" => "VUV", "name_en" => "VUV - Vanuatu Vatu", "name_ar" => null],
            ["code" => "VEF", "name_en" => "VEF - Venezuelan BolÃ­var", "name_ar" => null],
            ["code" => "VND", "name_en" => "VND - Vietnamese Dong", "name_ar" => null],
            ["code" => "YER", "name_en" => "YER - Yemeni Rial", "name_ar" => null],
            ["code" => "ZMK", "name_en" => "ZMK - Zambian Kwacha", "name_ar" => null],
        ];

        foreach ($currencies as $currency) {
            PublicCurrency::create($currency);
        }
    }
}
